version: "3.9"

services:
  db:
    image: postgres:15.15-alpine
    container_name: fastapi_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  redis:
    image: redis:8.4.0-alpine
    container_name: celery_redis

  web:
    build: .
    container_name: fastapi_web
    ports:
      - 8000:8000
    command: fastapi run
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:mysecretpassword@db:5432/mydb
      - DATABASE_URL_FOR_MIGRATION=postgresql://postgres:mysecretpassword@db:5432/mydb
      - LOG_LEVEL=DEBUG
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis

  worker1:
    build: .
    container_name: celery_worker1
    command: celery -A worker.celery worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:mysecretpassword@db:5432/mydb
      - DATABASE_URL_FOR_MIGRATION=postgresql://postgres:mysecretpassword@db:5432/mydb
      - LOG_LEVEL=DEBUG
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
    
  worker2:
    build: .
    container_name: celery_worker2
    command: celery -A worker.celery worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:mysecretpassword@db:5432/mydb
      - DATABASE_URL_FOR_MIGRATION=postgresql://postgres:mysecretpassword@db:5432/mydb
      - LOG_LEVEL=DEBUG
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
  
  flower:
    build: .
    container_name: celery_flower
    command: celery --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web

volumes:
  postgres_data:
